name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release --no-build
      - name: Pack
        run: dotnet pack --configuration Release --no-build --output ${{ env.NuGetDirectory }} /p:Version=${{ github.event.inputs.version }}
      - name: Push to nuget
        run: dotnet nuget push ${{ env.NuGetDirectory }}/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
      - name: Create git tag
        uses: EndBug/latest-tag@latest
        with:
          ref: ${{ github.event.inputs.version }}
      - name: Create github release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          draft: true